print("--- Kiosk Khai Báo Tự Phục Vụ ---")
patient_id = input ("Mã bệnh nhân: ")
patient_name = input ("Họ tên bệnh nhân: ")
heart_rate = int(input ("Nhịp tim: "))
body_temperature = float(input ("Nhiệt độ: "))
weight = float(input ("Cân nặng: "))
Kiosk_thu_thap_tu_dong = f"Mã bệnh nhân:{patient_id} - Tên bệnh nhân:{patient_name} - Nhịp tim:{heart_rate} - Nhiệt độ:{body_temperature} - Cân nặng:{weight}";

print(Kiosk_thu_thap_tu_dong)
print("Mã bệnh nhân: ", patient_id)
print("Kiểu dữ liệu đang dùng cho mã bệnh nhân", type(patient_id))
print("Họ tên bệnh nhân: ", patient_name)
print("Kiểu dữ liệu đang dùng cho tên bệnh nhân", type(patient_name))
print("Nhịp tim: ", heart_rate)
print("Kiểu dữ liệu đang dùng cho nhịp tim", type(heart_rate))
print("Nhiệt độ: ", body_temperature)
print("Kiểu dữ liệu đang dùng cho nhiệt độ", type(body_temperature))
print("Cân nặng: ", weight)
print("Kiểu dữ liệu đang dùng cho cân nặng", type(weight))